<body class="page-template-default page page-id-8958 pinel-loi-gouv__refonte elementor-default elementor-kit-7964 elementor-page elementor-page-8958">
    <div id="page_content">
        <div data-elementor-type="wp-page" data-elementor-id="8958" class="elementor elementor-8958" data-elementor-settings="[]">
            <div class="elementor-inner">
                <div class="elementor-section-wrap">
                    <section class="elementor-section elementor-top-section elementor-element elementor-element-5735b3e elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="5735b3e" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                        <div class="elementor-container elementor-column-gap-default">
                        <div class="elementor-row">
                            <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-0c98ed1" data-id="0c98ed1" data-element_type="column">
                                <div class="elementor-column-wrap elementor-element-populated">
                                    <div class="elementor-widget-wrap">
                                        <div class="elementor-element elementor-element-aa09ede elementor-widget elementor-widget-image" data-id="aa09ede" data-element_type="widget" data-widget_type="image.default">
                                            <div class="elementor-widget-container">
                                                <div class="elementor-image">
                                                    <a href="https://dynasty-patrimoine.com/">
                                                        <img width="139" height="35" src="img/logo.png" class="attachment-full size-full" alt="" loading="lazy" />														
                                                    </a>
                                                </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    
            <section class="elementor-section elementor-top-section elementor-element elementor-element-8f4709f elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="8f4709f" data-element_type="section">
                <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-row">
                        <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-f31d7d2" data-id="f31d7d2" data-element_type="column">
                            <div class="elementor-column-wrap elementor-element-populated">
                                <div class="elementor-widget-wrap">
                                    <div class="elementor-element elementor-element-5e29b42 elementor-widget elementor-widget-spacer" data-id="5e29b42" data-element_type="widget" data-widget_type="spacer.default">
                                        <div class="elementor-widget-container">
                                            <div class="elementor-spacer">
                                                <div class="elementor-spacer-inner"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>


            <section class="elementor-section elementor-top-section elementor-element elementor-element-87e45aa elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="87e45aa" data-element_type="section">
                <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-row">
                        <div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-f69f0f1" data-id="f69f0f1" data-element_type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                            <div class="elementor-column-wrap elementor-element-populated">
                                <div class="elementor-widget-wrap">
                                    <div class="elementor-element elementor-element-629ce67 elementor-widget elementor-widget-cc_tc_elementor_conseiller_photo_block" data-id="629ce67" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_photo_block.default">
                                        <div class="elementor-widget-container">
                                    </div>
                                </div>
                                    <div class="elementor-element elementor-element-1902754 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="1902754" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                                        <div class="elementor-widget-container">
                                        </div>
                            </div>
                            <div class="elementor-element elementor-element-17dd8a7 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="17dd8a7" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                            <div class="elementor-widget-container"></div>
                        </div>
            <div class="elementor-element elementor-element-861f628 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="861f628" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
            <div class="elementor-widget-container">
        <p><a href="mailto:"></a></p>		</div>
            </div>

            <section class="elementor-section elementor-inner-section elementor-element elementor-element-69b4dfb elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="69b4dfb" data-element_type="section">
                <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-row">
                        <div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-a4e206f" data-id="a4e206f" data-element_type="column">
                            <div class="elementor-column-wrap elementor-element-populated">
                                <div class="elementor-widget-wrap">
                            </div>
                        </div>
                    </div>
            <div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-4cc60fb" data-id="4cc60fb" data-element_type="column">
                <div class="elementor-column-wrap elementor-element-populated">
                    <div class="elementor-widget-wrap"></div>
                </div>
            </div>
            
                </div>
                </div>
            </section>


            <div class="elementor-element elementor-element-6400844 elementor-widget-divider--view-line elementor-widget elementor-widget-divider" data-id="6400844" data-element_type="widget" data-widget_type="divider.default">
                <div class="elementor-widget-container">
                    <div class="elementor-divider">
                    <span class="elementor-divider-separator"></span>
                </div>
            </div>

            </div>

        <div class="elementor-element elementor-element-42412b9 elementor-mobile-align-center elementor-hidden-desktop elementor-hidden-tablet elementor-widget elementor-widget-cc_tc_elementor_conseiller_button_block" data-id="42412b9" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_button_block.default">
            <div class="elementor-widget-container">
                <div class="elementor-button-wrapper">
                    <a href="#form-RDV" class="elementor-button-link elementor-button elementor-size-sm" role="button">
                        <span class="elementor-button-content-wrapper">
                            <span class="elementor-button-text">Programmer un RDV</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>

            <div class="elementor-element elementor-element-7a85d28 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="7a85d28" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                <div class="elementor-widget-container">
                    <p>Mes compétences</p>		
                </div>
            </div>

            <div class="elementor-element elementor-element-084f4b9 elementor-widget-divider--view-line elementor-widget elementor-widget-divider" data-id="084f4b9" data-element_type="widget" data-widget_type="divider.default">
                <div class="elementor-widget-container">
                    <div class="elementor-divider">
                        <span class="elementor-divider-separator"></span>
                    </div>
                </div>
            </div>

            <div class="elementor-element elementor-element-a7405cd elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="a7405cd" data-element_type="widget" data-widget_type="icon-list.default">
                <div class="elementor-widget-container">
                    <ul class="elementor-icon-list-items">
                        <li class="elementor-icon-list-item">
                        <span class="elementor-icon-list-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Calque_1" x="0px" y="0px" viewBox="0 0 20 20" style="enable-background:new 0 0 20 20;" xml:space="preserve">
                                <g>
                                    <path style="fill:#16466C;" d="M10,0.5c5.24,0,9.5,4.26,9.5,9.5s-4.26,9.5-9.5,9.5S0.5,15.24,0.5,10S4.76,0.5,10,0.5 M10,0   C4.48,0,0,4.48,0,10s4.48,10,10,10s10-4.48,10-10S15.52,0,10,0L10,0z"></path>
                                </g>
                                <g>
                                    <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="10" y1="3.79" x2="10" y2="16.21"></line>
                                </g>
                                <g>
                                    <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="3.79" y1="10" x2="16.21" y2="10"></line>
                                </g>
                            </svg>						
                        </span>
                            <span class="elementor-icon-list-text blue">Investissement immobilier</span>
                            </li>
                            <li class="elementor-icon-list-item">
                            <span class="elementor-icon-list-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Calque_1" x="0px" y="0px" viewBox="0 0 20 20" style="enable-background:new 0 0 20 20;" xml:space="preserve">
                                    <g>
                                        <path style="fill:#16466C;" d="M10,0.5c5.24,0,9.5,4.26,9.5,9.5s-4.26,9.5-9.5,9.5S0.5,15.24,0.5,10S4.76,0.5,10,0.5 M10,0   C4.48,0,0,4.48,0,10s4.48,10,10,10s10-4.48,10-10S15.52,0,10,0L10,0z"></path>
                                    </g>
                                    <g>
                                        <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="10" y1="3.79" x2="10" y2="16.21"></line>
                                    </g>
                                    <g>
                                        <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="3.79" y1="10" x2="16.21" y2="10"></line>
                                    </g>
                                </svg>						
                            </span>
                            <span class="elementor-icon-list-text blue">Aide à la déclaration de revenus</span>
                            </li>
                                <li class="elementor-icon-list-item">
                                <span class="elementor-icon-list-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Calque_1" x="0px" y="0px" viewBox="0 0 20 20" style="enable-background:new 0 0 20 20;" xml:space="preserve">
                                        <g>
                                            <path style="fill:#16466C;" d="M10,0.5c5.24,0,9.5,4.26,9.5,9.5s-4.26,9.5-9.5,9.5S0.5,15.24,0.5,10S4.76,0.5,10,0.5 M10,0   C4.48,0,0,4.48,0,10s4.48,10,10,10s10-4.48,10-10S15.52,0,10,0L10,0z"></path>
                                        </g>
                                        <g>
                                            <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="10" y1="3.79" x2="10" y2="16.21"></line>
                                        </g>
                                        <g>
                                            <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="3.79" y1="10" x2="16.21" y2="10"></line>
                                        </g>
                                    </svg>						
                                </span>

                                <span class="elementor-icon-list-text blue">Lois de défiscalisation</span>
                                </li>
                                <li class="elementor-icon-list-item">
                                    <span class="elementor-icon-list-icon">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Calque_1" x="0px" y="0px" viewBox="0 0 20 20" style="enable-background:new 0 0 20 20;" xml:space="preserve">
                                            <g>
                                                <path style="fill:#16466C;" d="M10,0.5c5.24,0,9.5,4.26,9.5,9.5s-4.26,9.5-9.5,9.5S0.5,15.24,0.5,10S4.76,0.5,10,0.5 M10,0   C4.48,0,0,4.48,0,10s4.48,10,10,10s10-4.48,10-10S15.52,0,10,0L10,0z"></path>
                                            </g>
                                            <g>
                                                <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="10" y1="3.79" x2="10" y2="16.21"></line>
                                            </g>
                                            <g>
                                                <line style="fill:none;stroke:#16466C;stroke-width:0.5;stroke-miterlimit:10;" x1="3.79" y1="10" x2="16.21" y2="10"></line>
                                            </g>
                                        </svg>		
                                    </span>
                                    <span class="elementor-icon-list-text blue">Courtage immobilier</span>
                            </li>
                        </ul>
                    </div>
                </div>

            <div class="elementor-element elementor-element-7feab97 elementor--h-position-center elementor--v-position-middle elementor-pagination-position-inside elementor-widget elementor-widget-slides" data-id="7feab97" data-element_type="widget" data-settings="{&quot;navigation&quot;:&quot;dots&quot;,&quot;autoplay_speed&quot;:3000,&quot;autoplay&quot;:&quot;yes&quot;,&quot;pause_on_hover&quot;:&quot;yes&quot;,&quot;pause_on_interaction&quot;:&quot;yes&quot;,&quot;infinite&quot;:&quot;yes&quot;,&quot;transition&quot;:&quot;slide&quot;,&quot;transition_speed&quot;:500}" data-widget_type="slides.default">
                <div class="elementor-widget-container">
                    <div class="elementor-swiper">
                        <div class="elementor-slides-wrapper elementor-main-swiper swiper-container" dir="ltr" data-animation="">
                            <div class="swiper-wrapper elementor-slides">
                                <div class="elementor-repeater-item-fb3a2a6 swiper-slide"><div class="swiper-slide-bg"></div><div class="swiper-slide-inner" ><div class="swiper-slide-contents"></div></div></div><div class="elementor-repeater-item-7180ed1 swiper-slide"><div class="swiper-slide-bg"></div><div class="swiper-slide-inner" ><div class="swiper-slide-contents"></div></div></div><div class="elementor-repeater-item-cbad617 swiper-slide"><div class="swiper-slide-bg"></div><div class="swiper-slide-inner" ><div class="swiper-slide-contents"></div></div></div>				</div>
                                    <div class="swiper-pagination"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

            <div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-cf34ffc" data-id="cf34ffc" data-element_type="column">
                <div class="elementor-column-wrap">
                    <div class="elementor-widget-wrap"></div>
                </div>
            </div>

            <div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-6c14c0d" data-id="6c14c0d" data-element_type="column">
                <div class="elementor-column-wrap elementor-element-populated">
                    <div class="elementor-widget-wrap">
                        <section class="elementor-section elementor-inner-section elementor-element elementor-element-60c0ce2 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="60c0ce2" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                            <div class="elementor-container elementor-column-gap-default">
                                <div class="elementor-row">
                                    <div class="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-239372c" data-id="239372c" data-element_type="column">
                                        <div class="elementor-column-wrap elementor-element-populated">
                                            <div class="elementor-widget-wrap">
                                                <div class="elementor-element elementor-element-cc7c062 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="cc7c062" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                                                    <div class="elementor-widget-container">
                                                        <p><span style="color: #000000;">Monsieur, Madame,</span></p><p><span class="blue">Spécialiste du Patrimoine, je vous accompagne pour construire à vos côtés un projet patrimonial cohérent avec votre profil et vos aspirations.</span></p><p><span style="color: #16466C;"><span style="color: #000000;">Avec une offre patrimoniale nourrie de 15 ans d’expérience, notre groupe propose des solutions pérennes et adaptées aux exigences des projets de chacun.</span></span></p>		</div>
                                                    </div>
                                                <div class="elementor-element elementor-element-59b0fab elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="59b0fab" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                                            <div class="elementor-widget-container">
                                                <p>  - Dynasty Patrimoine</p>	
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            <div class="elementor-element elementor-element-63d9314 elementor-widget elementor-widget-spacer" data-id="63d9314" data-element_type="widget" data-widget_type="spacer.default">
                <div class="elementor-widget-container">
                    <div class="elementor-spacer">
                        <div class="elementor-spacer-inner"></div>
                    </div>
                </div>
            </div>

            <section class="elementor-section elementor-inner-section elementor-element elementor-element-2704e74 elementor-reverse-mobile elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="2704e74" data-element_type="section">
                <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-row">
                        <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-9dc7b77" data-id="9dc7b77" data-element_type="column" id="form-RDV" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                            <div class="elementor-column-wrap elementor-element-populated">
                                <div class="elementor-widget-wrap">
                                    <div class="elementor-element elementor-element-b6081cb elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="b6081cb" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                                        <div class="elementor-widget-container">
                                            <p>Mes conseils sont offerts et sans engagement</p>		
                                        </div>
                                    </div>
            <div class="elementor-element elementor-element-1796a36 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="1796a36" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                <div class="elementor-widget-container">
                    <p class="blue">Programmons ensemble un rendez-vous </p>		
                </div>
            </div>

            <div class="elementor-element elementor-element-c62cb3c elementor-button-align-center elementor-widget elementor-widget-form" data-id="c62cb3c" data-element_type="widget" data-settings="{&quot;step_next_label&quot;:&quot;Next&quot;,&quot;step_previous_label&quot;:&quot;Previous&quot;,&quot;button_width&quot;:&quot;100&quot;,&quot;step_type&quot;:&quot;number_text&quot;,&quot;step_icon_shape&quot;:&quot;circle&quot;}" data-widget_type="form.default">
                <div class="elementor-widget-container">
                    <span class='formErrors'><?php if(isset ( $errors)){echo  $errors;}?></span>
                    <form  class="elementor-form" method="POST"  name="Demande RDV accompagnement Dyasty Patrimoine">
                        <div class="elementor-form-fields-wrapper elementor-labels-above">

                        <div class="elementor-field-type-text elementor-field-group elementor-column elementor-field-group-nom elementor-col-50 elementor-field-required">
                            <label for="form-field-nom" class="elementor-field-label">Nom</label>
                            <input size="1" type="text" name="name" id="form-field-nom" class="elementor-field elementor-size-sm  elementor-field-textual" required="required" aria-required="true">
                        </div>

                        <div class="elementor-field-type-number elementor-field-group elementor-column elementor-field-group-telephone elementor-col-50 elementor-field-required">
                            <label for="form-field-telephone" class="elementor-field-label">Téléphone</label>
                            <input type="number" name="telephone" id="form-field-telephone" class="elementor-field elementor-size-sm  elementor-field-textual" required="required" aria-required="true" min="" max="" >
                        </div>

                        <div class="elementor-field-type-email elementor-field-group elementor-column elementor-field-group-email elementor-col-50 elementor-field-required">
                            <label for="form-field-email" class="elementor-field-label">Email</label>
                            <input size="1" type="email" name="email" id="form-field-email" class="elementor-field elementor-size-sm  elementor-field-textual" required="required" aria-required="true">
                        </div>
                        <div class="elementor-field-type-number elementor-field-group elementor-column elementor-field-group-codepostal elementor-col-50 elementor-field-required">
                            <label for="form-field-codepostal" class="elementor-field-label">Code Postal</label>
                            <input type="number" name="codePostal" id="form-field-codepostal" class="elementor-field elementor-size-sm  elementor-field-textual" required="required" aria-required="true" min="" max="" >
                        </div>

                        <div class="elementor-field-type-date elementor-field-group elementor-column elementor-field-group-date_souhaitee elementor-col-50 elementor-field-required">
                            <label for="form-field-date_souhaitee" class="elementor-field-label">Date souhaitée</label>
                            <input type="date" name="date" min='2000-13-13' id="form-field-date_souhaitee" class="elementor-field elementor-size-sm  elementor-field-textual elementor-date-field" required="required" aria-required="true" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}">
                        </div>

                        <div class="elementor-field-type-time elementor-field-group elementor-column elementor-field-group-heure_souhaitee elementor-col-50 elementor-field-required">
                            <label for="form-field-heure_souhaitee" class="elementor-field-label">Heure souhaitée</label>
                            <input type="time" name="hour" id="form-field-heure_souhaitee" class="elementor-field elementor-size-sm  elementor-field-textual elementor-time-field elementor-use-native" required="required" aria-required="true">
                        </div>

                        <div class="elementor-field-type-text elementor-field-group elementor-column elementor-field-group-pseudo_skype elementor-col-100">
                            <label for="form-field-pseudo_skype" class="elementor-field-label">Type de rendez-vous</label>
                            <select name="pseudoSkype" class="elementor-field elementor-size-sm  elementor-field-textual" id="form-field-pseudo_skype">
                                <option value="Visio">Visio</option>
                                <option value="Téléphonique">Téléphonique</option>
                                <option value="Physique">Physique</option>
                            </select>
                        </div>

                        <div class="elementor-field-group elementor-column elementor-field-type-submit elementor-col-100 e-form__buttons">
                            <button type="submit" name="contact" class="elementor-button elementor-size-sm">
                                <span>
                                    <span class=" elementor-button-icon"></span>
                                    <span class="elementor-button-text">Confirmer mon RDV</span>
                                </span>
                            </button>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
        <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-2f029a2" data-id="2f029a2" data-element_type="column">
            <div class="elementor-column-wrap">
                <div class="elementor-widget-wrap"></div>
            </div>
        </div>

            <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-691435b elementor-hidden-tablet" data-id="691435b" data-element_type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                <div class="elementor-column-wrap elementor-element-populated">
                    <div class="elementor-widget-wrap">
                        <div class="elementor-element elementor-element-2c178c4 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="2c178c4" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                            <div class="elementor-widget-container">
                                <p class="blue">Pourquoi organiser un rendez-vous d'accompagnement ?</p>	
                            </div>
                        </div>
            <div class="elementor-element elementor-element-278b777 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="278b777" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                <div class="elementor-widget-container">
                    <p><strong>1 - Identifier vos objectifs patrimoniaux</strong></p><p><strong>2 - Comprendre et appliquer les options possibles pour optimiser mes impôts et mes investissements</strong></p><p><strong>3 - Bénéficier d'un accompagnement global</strong></p>		</div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

</section>
<section class="elementor-section elementor-inner-section elementor-element elementor-element-fe0bcda elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="fe0bcda" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
    <div class="elementor-container elementor-column-gap-default">
        <div class="elementor-row">
            <div class="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-5944496" data-id="5944496" data-element_type="column">
                <div class="elementor-column-wrap elementor-element-populated">
                    <div class="elementor-widget-wrap">
                        <div class="elementor-element elementor-element-74289e3 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="74289e3" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                            <div class="elementor-widget-container">
                                <p class="blue">Dynasty Patrimoine,<br /><strong>qui sommes-nous ?</strong></p>	
                            </div>
                        </div>

                    <div class="elementor-element elementor-element-d3e2aaf elementor-widget-divider--view-line elementor-widget elementor-widget-divider" data-id="d3e2aaf" data-element_type="widget" data-widget_type="divider.default">
                        <div class="elementor-widget-container">
                            <div class="elementor-divider">
                                <span class="elementor-divider-separator"></span>
                            </div>
                        </div>
                    </div>

                    <div class="elementor-element elementor-element-7ed3b35 elementor-widget elementor-widget-cc_tc_elementor_conseiller_editor_block" data-id="7ed3b35" data-element_type="widget" data-widget_type="cc_tc_elementor_conseiller_editor_block.default">
                        <div class="elementor-widget-container">
                            <p><span>Dyasty Patrimoine sélectionne de façon rigoureuse les opportunités du marché afin de vous apporter des solutions de défiscalisation sur-mesure, rentables et durables.</span></p>		</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

    <section class="elementor-section elementor-inner-section elementor-element elementor-element-868000e elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="868000e" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
        <div class="elementor-container elementor-column-gap-default">
        <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-6c2af6e" data-id="6c2af6e" data-element_type="column">
            <div class="elementor-column-wrap elementor-element-populated">
                <div class="elementor-widget-wrap">
                    <div class="elementor-element elementor-element-b33aff8 elementor-widget elementor-widget-heading" data-id="b33aff8" data-element_type="widget" data-widget_type="heading.default">
                        <div class="elementor-widget-container">
                            <h2 class="elementor-heading-title elementor-size-default">+15</h2>
                        </div>
                    </div>

                    <div class="elementor-element elementor-element-7b44dd2 elementor-widget elementor-widget-text-editor" data-id="7b44dd2" data-element_type="widget" data-widget_type="text-editor.default">
                        <div class="elementor-widget-container">
                            <div class="elementor-text-editor elementor-clearfix">
                                <p>d'expérience</p>					
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-6c2af6e" data-id="6c2af6e" data-element_type="column">
            <div class="elementor-column-wrap elementor-element-populated">
                <div class="elementor-widget-wrap">
                    <div class="elementor-element elementor-element-b33aff8 elementor-widget elementor-widget-heading" data-id="b33aff8" data-element_type="widget" data-widget_type="heading.default">
                        <div class="elementor-widget-container">
                            <h2 class="elementor-heading-title elementor-size-default">+20</h2>
                        </div>
                    </div>

                    <div class="elementor-element elementor-element-7b44dd2 elementor-widget elementor-widget-text-editor" data-id="7b44dd2" data-element_type="widget" data-widget_type="text-editor.default">
                        <div class="elementor-widget-container">
                            <div class="elementor-text-editor elementor-clearfix">
                                <p>collaborateurs</p>					
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
    <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-6bffe3e" data-id="6bffe3e" data-element_type="column">
        <div class="elementor-column-wrap elementor-element-populated">
            <div class="elementor-widget-wrap">
                <div class="elementor-element elementor-element-b2504af elementor-widget elementor-widget-heading" data-id="b2504af" data-element_type="widget" data-widget_type="heading.default">
            <div class="elementor-widget-container">
                <h2 class="elementor-heading-title elementor-size-default">+1000</h2>
            </div>
        </div>
            <div class="elementor-element elementor-element-59d3752 elementor-widget elementor-widget-text-editor" data-id="59d3752" data-element_type="widget" data-widget_type="text-editor.default">
                <div class="elementor-widget-container">
                    <div class="elementor-text-editor elementor-clearfix">
                        <p> clients</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        
    <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-5b5458b" data-id="5b5458b" data-element_type="column">
        <div class="elementor-column-wrap elementor-element-populated">
            <div class="elementor-widget-wrap">
                <div class="elementor-element elementor-element-efeeee0 elementor-widget elementor-widget-heading" data-id="efeeee0" data-element_type="widget" data-widget_type="heading.default">
                    <div class="elementor-widget-container">
                        <h2 class="elementor-heading-title elementor-size-default">+3000</h2>
                    </div>
                </div>
                <div class="elementor-element elementor-element-f5b8bc8 elementor-widget elementor-widget-text-editor" data-id="f5b8bc8" data-element_type="widget" data-widget_type="text-editor.default">
                    <div class="elementor-widget-container">
                        <div class="elementor-text-editor elementor-clearfix">
                            <p>supports financiers</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</section>
</div>
</div>
</div>
    <div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-5b9e29a" data-id="5b9e29a" data-element_type="column">
        <div class="elementor-column-wrap">
            <div class="elementor-widget-wrap"></div>
        </div>
    </div>
</div>
</div>
</section>

