<!DOCTYPE html>
<html lang="fr-FR">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />
    <title>Mon conseiller Dynasty Patrimoine</title>
    <meta name="description" content="Les conseillers Dyasty Patrimoine sont à votre disposition pour répondre à vos question sur l&#039;épargne, l&#039;immobilier, le patrimoine. Prenez RDV en ligne" />
    <link rel="stylesheet" href="css/ctrlC.css">
    <link rel="stylesheet" href="css/style.css">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" type="images/vg" sizes="16x16" href="img/favicon.png">
	</head>
  
  <body>
    <main>
      <?php require $page ?>
    </main>
    <script src="./js/app.js"></script>
  </body>
</html>
<!-- Formulaire realisé pour signature email -->
<!-- Réalisation de la signature 
1.Parametres gmail
2.Signature
3.Ajouter un lien
4.Passer dans l'url ceci https://dynasty-patrimoine.com/ProgrammerUnRDV/index.php?email=ainalagrande@dynasty-patrimoine.com
5.Remplacer l'email par le votre
6.Attention! l'email entré doit être lié à un serveur web 
-->
<!-- ©Copyright Aïna LAGRANDE  -->

